Added new mixins
brack3t/django-braces pull request #270
Opened 2021-09-27 14:50 UTC by null-none

Added NeverCacheMixin, CacheMixin and CacheControlMixin.

2021-09-29 13:33 UTC, null-none commented
Added timezone mixin

2021-10-03 15:48 UTC, auvipy requested changes

2021-10-03 15:48 UTC, auvipy commented on mixin/views/_other.py
> +class PaginatorMixin(object):
object is not needed

2021-10-03 15:48 UTC, auvipy commented on mixin/views/_other.py
> +class TimezoneMixin(object):
object no needed

2021-10-03 15:48 UTC, auvipy commented on mixin/views/_other.py
> +class NeverCacheMixin(object):
object not needed

2021-10-03 15:48 UTC, auvipy commented on mixin/views/_other.py
> +        return super(NeverCacheMixin, self).dispatch(*args, **kwargs)
only super() should be ok

2021-11-04 20:32 UTC, closed without merging